services:
  # Spring Boot Application
  spring-app:
    image: your-docker-image-name:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - h2-database

  # H2 Database
  h2-database:
    image: "h2database/h2:latest"
    ports:
      - "9092:9092"
    environment:
      - H2_TCP_ALLOW_OTHERS=true
